### ISSUE TITLE
SysML Block are not shown properly

### ISSUE THREAD

**Issue by bowie2211** [ModelioOpenSource/Modelio#105]
The Blocks in my SysML Projekt look really strange in a block defintion diagram.

![Strange_Block Definition diagram](https://github.com/user-attachments/assets/d4f16ccd-da7c-4692-a255-c07237399d26)

**Comment by IrinaNeculita** [comment]
Hello,
When you create the blocks just click in diagram, don't do the draw creation. 
![modelio_J9dFiC4bwV](https://github.com/user-attachments/assets/eb2cf8d7-f12a-4551-b46a-6748f74bf642)

Regards, 
Irina

**Comment by bowie2211** [comment]
Hi Irina,
when I open "The plant" and go to the BDD-SystemStructure and add Blocks to it a get an expected behavior.
Like this
![grafik](https://github.com/user-attachments/assets/23173163-533b-4e93-a5e6-e25a33623a37)

If I add a packge and add a BDD to this package, Blocks and Ports are displayed like this.
![grafik](https://github.com/user-attachments/assets/35a4c6bd-bf7c-4c23-b6c2-cbb21764915f)

For me this is a strange graphical representation of a Block in a BDD, I would prefer the one in the upper picture.

Or is there a speciacl setting required to get the result in the first screenshot?

Thank you.

Regs Marcus



Regs Marcus

**Comment by IrinaNeculita** [comment]
Hi,
The representation mode can be changed from the Symbol view. On the first image, you have the structured mode; the second is the image mode. 
![modelio_WcHuLf9Pho](https://github.com/user-attachments/assets/f0c7afba-a7da-42d9-a955-4c626dc17ab5)

**Comment by bowie2211** [comment]
Hi Irina,
when I open "The plant" and go to the BDD-SystemStructure and add Blocks to it a get an expected behavior.
Like this
![grafik](https://github.com/user-attachments/assets/23173163-533b-4e93-a5e6-e25a33623a37)

If I add a packge and add a BDD to this package, Blocks and Ports are displayed like this.
![grafik](https://github.com/user-attachments/assets/35a4c6bd-bf7c-4c23-b6c2-cbb21764915f)

For me this is a strange graphical representation of a Block in a BDD, I would prefer the one in the upper picture.

Or is there a speciacl setting required to get the result in the first screenshot?

Thank you.

Regs Marcus



Regs Marcus

**Comment by IrinaNeculita** [comment]
> Hi Irina, when I open "The plant" and go to the BDD-SystemStructure and add Blocks to it a get an expected behavior. Like this ![grafik](https://private-user-images.githubusercontent.com/38601387/351052354-23173163-533b-4e93-a5e6-e25a33623a37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzcxOTMsIm5iZiI6MTcyMTgzNjg5MywicGF0aCI6Ii8zODYwMTM4Ny8zNTEwNTIzNTQtMjMxNzMxNjMtNTMzYi00ZTkzLWE1ZTYtZTI1YTMzNjIzYTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE2MDEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNDg2YWU3Mzg0YWViOTA2YThkY2FkMmI4MTk3MjFkMGU5MGViNGMwODc0ZTc0ODRhMzczNGQ2MjBjMmUwZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F7YhTWS6L-TLbflnzsz6XwrPMh-8q-rZ7NbZh4R7uNc)
> 
> If I add a packge and add a BDD to this package, Blocks and Ports are displayed like this. ![grafik](https://private-user-images.githubusercontent.com/38601387/351052788-35a4c6bd-bf7c-4c23-b6c2-cbb21764915f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzcxOTMsIm5iZiI6MTcyMTgzNjg5MywicGF0aCI6Ii8zODYwMTM4Ny8zNTEwNTI3ODgtMzVhNGM2YmQtYmY3Yy00YzIzLWI2YzItY2JiMjE3NjQ5MTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE2MDEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MDY4OTgxMmFkMDk1YjQ5Mjk3NjI2YjE2MzE4ZDNhMmNjOTcyYzU5NWIyZjI0YzFhZjJkMzZjY2UyNjQ3ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QifganRRYXimyd-82KMUNo-nPK5qQIDVm3gw-2oc8Ik)
> 
> For me this is a strange graphical representation of a Block in a BDD, I would prefer the one in the upper picture.
> 
> Or is there a speciacl setting required to get the result in the first screenshot?
> 
> Thank you.
> 
> Regs Marcus
> 
> Regs Marcus

Have you try to change the representation mode?

**Comment by bowie2211** [comment]
Thank you!
Next time I dig deeper into the documentation.

Regs Marcus
