### ISSUE TITLE
Windows 11 Installation ambigious error message

### ISSUE THREAD

**Issue by ytatichno** [ModelioOpenSource/Modelio#112]
My problem is not critical(and I actually solved it).
I tried to install Modelio 5.4.1 to C:\Program files\Modelio folder on my Win11 system and the error message poped up at the beggining of the installation process.
It looks like
```
 ______________________________________________
|(ico)Modelio Open Source 5.4 Setup          X |
|----------------------------------------------|
|                                              |
| \/    Error opening file for writing:        |
| /\                                           |
|       C:\Program Files\Modelio\concrt140.dll |
|                                              |
|       Click Abort to stop the installation,  |
|       Retry to try again, or                 |
|       Ignore to skip this file.              |
|                                              |
|----------------------------------------------|
|           _____     _____     ______         |
|          |Abort|   |Retry|   |Ignore|        |
|______________________________________________|
```
In my case:
Abort stops the Installation
Retry close reopen this modal without changes
Ignore reopen this modal with files of [modelio.exe, modelio.ini, msvcp100.dll, msvcp140.dll, ...]

But I have done successful installation at C:\Users\username\modelio\Modelio Open Source 5.4 installer suggested it by default.

I've found if I run installer as Admin(and it won't run installer as admin by default) it will suggest C:\Program Files\Modelio Open Source 5.4 and it successfully installs Modelio there.
I think installer must require admin permission in this case. I thought I gived permission when I aclually gived it to create folder "modelio" in Program Files.

Sorry if my issue not very serious, but it take a few minutes to came up with idea to run installer as Admin.

**Comment by IrinaNeculita** [comment]
Hi,
I can install in both folders: the default folder and a new created folder. 
Irina.
