### ISSUE TITLE
How to create class diagram's attribute without visible type ?

### ISSUE THREAD

**Issue by martinkunc** [ModelioOpenSource/Modelio#114]
Hi, thank you for all your hard work on Modelio.

I wanted to ask, is it possible to create an attribute in a class diagram where the type woudn't be displayed at all ?

Currently I can use <null>, which shows <no type>, but in my conceptual diagram I wanted to show no attribute type at all.
Here is how it looks for me:

![image](https://github.com/user-attachments/assets/a26abeb5-96ee-4054-ba04-10d816b9a0b5)

Thank you, Martin

**Comment by etiennebrosse** [comment]
Hi Martin,

For now, attribute type are mandatory. 
So it is only possible to show an attribut with its type or not the attribut at all.

Best,
EBR
