### ISSUE TITLE
Aesthetic Issue I want to work on

### ISSUE THREAD

**Issue by BurgundyWillow** [ModelioOpenSource/Modelio#19]
Aesthetic issue:

I would like to put borders around the blocks in the block definition, the way it is designed in the SysML standard guide.(page 32),
So, I am creating this issue to work on.

**Comment by IrinaNeculita** [comment]
Hi,
Can create the block definition diagram under a package, unmask the package in diagram and than create the element. 
Or if you need it just visual can use the free drawing. 
![modelio_OjA9WnVhB2](https://user-images.githubusercontent.com/130666068/236841530-d6e51df7-b1d4-4de2-baaa-d654ec4c3517.png)

![modelio_CVsi9sjUkD](https://user-images.githubusercontent.com/130666068/236841949-db955e5a-952d-4aa2-9be6-2cfd3f5f907d.png)
