### ISSUE TITLE
Communication diagram message direction

### ISSUE THREAD

**Issue by hummel-32** [ModelioOpenSource/Modelio#23]
Dear developers,

currently I am creating a larger _Communication diagram_ and I am experiencing the same problem almost every time I try to create _Communication Messages_ on _Communication Channels_ connecting _Communication Nodes_.

When I try to create a _Communication Message_ in a specific direction, I select the _Communication Message_ tool and click on the _Communication Channel_ as close as possible to a _Communication Node_. (cmp. https://www.modelio.org/forum/7-general-help/2844-communication-message-arrows-in-communication-diagram.html)

It does not matter which node I click close to, the _Communication Message_ is always created in the same direction.
I have even moved around the nodes like crazy but I could not get the messages to face in a specific direction.

Affected version:
Version 4.1.00
Build: 202009292130
System: win32 (10.0) 
Architecture: x86_64

Best regards
Hummel-32

**Comment by IrinaNeculita** [comment]
Hi,
I testes on 4.1 also 5.3.1 and it works. 
![modelio_cAOQBl8gGh](https://user-images.githubusercontent.com/130666068/235136570-ec4d8c96-84ca-47e8-a898-6717618f5be9.png)
