### ISSUE TITLE
Bad link SysML Architect (open source)

### ISSUE THREAD

**Issue by tellts** [ModelioOpenSource/Modelio#32]
On the page https://store.modelio.org/resource/modules/sysml-architect-open-source.html
and https://www.modelio.org/tutorials/how-to-create-sysml-diagrams-in-modelio.html
download links
http://forge.modelio.org/projects/sysml/files
http://www.modeliosoft.com/en/modelio-store/modules/modeling-extensions/sysml-architect-open-source.html

**Comment by etiennebrosse** [comment]
You are right.

SysML Architect is available from:
https://github.com/ModelioOpenSource/ExtensionsForModelio/releases/tag/5.3.1

**Comment by tellts** [comment]
Thank You!
