### ISSUE TITLE
Provide instructions on how to make use of 5.1 source release

### ISSUE THREAD

**Issue by olberger** [ModelioOpenSource/Modelio#34]
A new 5.1 release just appeared at https://github.com/ModelioOpenSource/Modelio/releases/tag/v5.1.0

However, there's no info I could spot that would explain how to build or run anything from this.

Maybe some maven oriented commands, as there's a pom.xml in the root dir ?

Thanks in advance.

**Comment by jcbritobr** [comment]
Also, why not just deploy an installer?

**Comment by yuuyins** [comment]
that's in the wiki https://github.com/ModelioOpenSource/Modelio/wiki/Build-Modelio-Index

here https://github.com/ModelioOpenSource/Modelio/wiki/Package_modelio

in 5.1 there isn't AGGREGATOR anymore, the pom.xml is in the root directory and you just run mvn in the root directory.

plus see https://github.com/ModelioOpenSource/Modelio/issues/38, so you probably will need to use my https://github.com/yuuyins/Modelio/commit/04fdda793f8ef191ff11ae9f633e07c052fc28bc.path
