### ISSUE TITLE
Unusable on Ubuntu 22.04.

### ISSUE THREAD

**Issue by daninsky1** [ModelioOpenSource/Modelio#36]
The 4.1 .deb package missing, from previous ubuntu releases, dependencies that cannot be easily satisfiable. 5.1 release has no .deb packages and reading the compilation process I just could not figure out how to compile this... thing.

**Comment by cyril72** [comment]
Hello, I am unable to install version 5 under ubuntu 22.04. Can you help me ? Thanks

**Comment by daninsky1** [comment]
Since then they have an updated .deb package, but still it needs libwebkit:
https://github.com/ModelioOpenSource/Modelio/releases/tag/v5.1.0
