### ISSUE TITLE
[5.1] Where's Archimate?

### ISSUE THREAD

**Issue by MrMoronIV** [ModelioOpenSource/Modelio#45]
hi,

How would I go and activate archimate? It's advertised on the starting page as supported, but I can't find it anywhere, nor as a plugin or in the program itself.

thanks

**Comment by etiennebrosse** [comment]
Hi,

You can find it here: https://www.modeliosoft.com/en/download/download-archimate.html

**Comment by IrinaNeculita** [comment]
Hi, 
On the page https://github.com/ModelioOpenSource/Modelio  you have the ArchiMate 3.2 Support leading to this page 
https://www.modeliosoft.com/en/download/download-archimate.html
