### ISSUE TITLE
Set the location of the project at the time of its creation

### ISSUE THREAD

**Issue by it19862** [ModelioOpenSource/Modelio#49]
**Now.**
I'm creating a project.
The project is being created.
In which folder is the project being created?

**Expectation.**
I click "Create Project".
Modelio asks which folder to place the project in.
I choose the folder where I want to place the project.
Modelio creates a project in the folder I need.

**Now.**
![01 02 2023_22-52-32](https://user-images.githubusercontent.com/18245828/216150814-f85b4715-a178-45ab-9f3b-9185d266c21e.png)

![01 02 2023_22-52-57](https://user-images.githubusercontent.com/18245828/216150840-ec712630-67e0-4fe5-8282-9b978f39e8b4.png)

![01 02 2023_22-53-25](https://user-images.githubusercontent.com/18245828/216150850-894a65b6-3272-4e92-9805-58a49957a236.png)

**Comment by IrinaNeculita** [comment]
Hello,
Before creating a project use "Switch Workspace", set the new directory and the projects will be created there. 
Default projects are created under "C:\Users\User\modelio\workspace".
