### ISSUE TITLE
Hide the decision input behavior

### ISSUE THREAD

**Issue by RalfEbert2** [ModelioOpenSource/Modelio#50]
Hi There,

in my activity diagrams, I show the name of a decision, which I can do by activating the option Show label in the Symbol dialog. Unfortunately, the Decision input behavior of the decision is also shown there, even if this field is empty in the properties. If I mask the note containing the Decision input behavior with the Mask function, the whole decision will be masked.

Is it possible to add this feature to hide only the Decision input behavior?

Used version of ModelIO:

    Version 5.1.00
    Build: 202207062130
    System: win32 (10.0)
    Architecture: x86_64
    
Best regards,
  Ralf Ebert

**Comment by IrinaNeculita** [comment]
Hello,
Thank you for reporting this issue, it has been forwarded to the Modelio development team. 

Regards,
Irina

**Comment by IrinaNeculita** [comment]
Hello, 
Now the line is displayed as a note.  Actually it represent the decision input behavior, so far it is only displayed with the label.

![frWw4N6pCp](https://github.com/ModelioOpenSource/Modelio/assets/130666068/44f77e94-74e4-4f13-bbf3-6c89e9fab373)

Regards, 
Irina
