### ISSUE TITLE
modelio.org is down

### ISSUE THREAD

**Issue by jorgeyanesdiez** [ModelioOpenSource/Modelio#52]
This is just a heads up.
It seems that modelio.org and store.modelio.org are down and have been like that for a few days. Looks like the domain registration expired.

**Comment by SuperGuerreiro** [comment]
I confirm this, can't check the API documentation...

**Comment by SuperGuerreiro** [comment]
Hey,

Thanks for the quick response!

However, it seems that the javadoc is not accessible, as it was hosted in modelio.org, is there any alternative way to access it in the meantime?

Thank you.

**Comment by aabherve** [comment]
Oh, you are right, we did not think about the rehosting of the javadoc during the interruption.

You can find the api under the link below:

https://www.modeliosoft.com/modeliosaas-help/510/fr/topic/com.modeliosoft.modelio.documentation.modelioapi/html/overview-summary.html?cp=11

This is the api for the commercial version of Modelio but all the entries in "org" correspond to the open source version of the api.

Regards.

**Comment by julienmerienne** [comment]
> Oh, you are right, we did not think about the rehosting of the javadoc during the interruption.
> 
> You can find the api under the link below:
> 
> https://www.modeliosoft.com/modeliosaas-help/510/fr/topic/com.modeliosoft.modelio.documentation.modelioapi/html/overview-summary.html?cp=11
> 
> This is the api for the commercial version of Modelio but all the entries in "org" correspond to the open source version of the api.
> 
> Regards.

The link provided is for version 5.1 of API.
In my case, we are still using the old 3.4.1 version of modelio, and i need the 3.4 api javadoc.
Is there any way for me to access it again ?

Regards.
