### ISSUE TITLE
How to reach SetFillAlpha function

### ISSUE THREAD

**Issue by acceliance** [ModelioOpenSource/Modelio#53]
Hi

After creating a graphic rectangle I cannot reach setFillMode function.

Here the code:
IDiagramGraphicFactory gf;
IDiagramDrawingsLayer layer;
IDiagramDrawingNode ddn = gf.createDrawingRectangle ( layer, null, 0, ypos, 0, 0);
ddn.setFillMode ( 1 ); // OK
ddn.setFillAlpha ( 1000 ); // KO

Thank you for your support, José

**Comment by aabherve** [comment]
Hi,

Not all graphic properties of the elements are equipped with direct accessors.
In case of properties without direct accessors, you have to use the generic accessor setProperty(Key,Value)  

In your case : 
ddn.setProperty("FILLALPHA", "0"); // value ["0"-"255"]

The name of the keys is unfortunately poorly documented: you can find these keys in the code ( class 'ElementName'StyleKeys)

**Comment by acceliance** [comment]
Thank you very much, the FILLALPHA property appears visually inside the diagram editor of Modelio so that'a a first level of documentation :-)
