### ISSUE TITLE
Java project option doesnt appear in Modelio 5.3.1

### ISSUE THREAD

**Issue by ejgutierrez74** [ModelioOpenSource/Modelio#57]
When i want to create a new project, with java designer and java profile, in version 5.1 appear an option to enable Java.

In 5.3.1 when you select new project, this option doesnt appear so you cant generate the java code.

Hope this could be fixed soon.

**Comment by aabherve** [comment]
In Modelio 5.3.1, this option has been removed so as to align the way java project extensions are handled with other types of projects extensions.

To create a Java project, you must deploy the JavaDesigner module in a new project from the module configuration page.
If the java module is not present in your module catalog, this one can be downloaded at this url: https://github.com/ModelioOpenSource/ExtensionsForModelio/releases/tag/5.3.1

![image](https://user-images.githubusercontent.com/15227604/229436677-66dc0d04-853a-4747-a781-e51052c681fc.png)

**Comment by ejgutierrez74** [comment]
And is there any place to read the documentation, because i couldnt read this change.

1 - So when i create a new project, in modules i have to assigna/add the java designer module if i want to work in Java . I did this way, dont know if its ritght:

First of all i create the project and then go to configuration of modules of the project:
![imagen](https://user-images.githubusercontent.com/11474846/230884485-abe44586-4db4-4eb5-9dd9-a0a0f21000d9.png)

And finally add java designer module ;
![imagen](https://user-images.githubusercontent.com/11474846/230884352-aeb5be2f-0d30-4d62-be46-c262d6f515f9.png)

Is this right ?

2 - When you generate the java code, the .java files doesnt appear in the project ? How can i find them ? Would be nice to have some kind of code or project code folder with this files. Easy to use and find. Also would be nice to add a project explorer / code generated files to read and edit them inside Modelio.

Thanks
