### ISSUE TITLE
Ubuntu + v5.3.1

### ISSUE THREAD

**Issue by jorgeyanesdiez** [ModelioOpenSource/Modelio#58]
Does v5.3.1 still require libwebkit under Ubuntu? I just installed with the latest deb and it seems to work, but then when I open the app it looks like this. Am I missing something?

![image](https://user-images.githubusercontent.com/1261722/229586781-b1b7ee40-8b2f-41ef-b77a-a30066b4df79.png)

**Comment by modelio-cde** [comment]
Hi Jorge,

Yes, the libwebkit2gtk-4.0 must be installed for Ubuntu 20/22.

Best regards,
cde.

**Comment by jorgeyanesdiez** [comment]
Thank you
