### ISSUE TITLE
BPMN Data Store

### ISSUE THREAD

**Issue by gpremelc** [ModelioOpenSource/Modelio#60]
Hello.
ModelioOpenSource doesn't provide the DataStore BPMN modelling element. Am I wrong ? 
It'd be nice to get it.
Regard,
Gildas

**Comment by IrinaNeculita** [comment]
Hello, 
We have on BPMN process diagram the "DataStore" element.

Regards,
Irina. 

![modelio_4albA9zAtX](https://user-images.githubusercontent.com/130666068/231764024-fc52db3c-77cd-4163-9e6e-b28115c6e82b.png)

**Comment by gpremelc** [comment]
Thank You Irina.
I was expecting data store element could be use on collaboration diagram to share data across processes.
It seems BPMN2 is confusing about this topic.
Gildas
