### ISSUE TITLE
Modelio.exe was blocked by anti-virus, infected by IDP.Generic

### ISSUE THREAD

**Issue by onepack** [ModelioOpenSource/Modelio#63]
After I added the Archimate add-on things went wrong when opening Modelio.

I got a virus warning.

<img width="461" alt="Screenshot 2023-04-24 163032" src="https://user-images.githubusercontent.com/475598/234030483-b919f554-880a-42b3-b7a6-5322b552e243.png">

After I uninstalled the App I was not able to install it again.
It keeps on giving me the error that the .exe is infected.

Platform: Win 11 + Modelio 5.3.1

**Comment by IrinaNeculita** [comment]
Hi, 
Avast has lots of false positive reports. 

https://forum.avast.com/index.php?topic=234761.0

Could you try to add modelio.exe as an exception for Avast and try to reinstall. 

Regards, 
Irina
