### ISSUE TITLE
can not set fork join to vertical

### ISSUE THREAD

**Issue by barnabashub** [ModelioOpenSource/Modelio#65]
In activity diagrams the fork join element stays horizontal, can not change to vertical

**Comment by IrinaNeculita** [comment]
Hello,
Thank you for reporting this issue, it has been forwarded to the Modelio development team.

Regards,
Irina.

**Comment by BigSchtroumpf** [comment]
Did you try the "orientation" option in the symbol property view ?
This works for me in v 5.4.01

- select the join in the diagram
- unfold the symbol property view (on the right of the diagram)
- set the "orientation" to either vertical or horizontal.

**Comment by etiennebrosse** [comment]
Fixed in Modelio 5.4.1
