### ISSUE TITLE
change order of attributes and operation in an uml class diagram

### ISSUE THREAD

**Issue by Neumann-Kohai** [ModelioOpenSource/Modelio#77]
is it possible to change order of attributes and operation in an uml class diagram?

If so, how do I do it?

**Comment by IrinaNeculita** [comment]
Hello,
You can change the order of operations and attributes.
Select the class : go to symbol view : set the **automatic content** on **manual**
In explorer move the operation/attributes as you wish using the move up/down arrows.
See attached gif. 

![modelio_52aO1Nd7nD](https://github.com/ModelioOpenSource/Modelio/assets/130666068/1211ffc8-fad3-4e50-877d-bcb048a3bec7)

Hope the information is useful.
Regards, 
Irina.
