### ISSUE TITLE
Duplicate Element

### ISSUE THREAD

**Issue by BurningDev** [ModelioOpenSource/Modelio#78]
Among other things, I use Modelio to create class and activity diagrams. However, I'm missing a function that allows me to duplicate existing elements (e.g. a class element in a UML class diagram).

**Comment by IrinaNeculita** [comment]
Hello,
In explorer you have the option to clone the element, all the sub elements/attributes/operations/settings are cloned.
Than by drag and drop the element is unmasked in diagram. 


The sibling option just creates a new standard class. 

See attached gif. 


![modelio_fY0tqWfhzO](https://github.com/ModelioOpenSource/Modelio/assets/130666068/603c9efa-3c84-46cc-9978-92182fa11168)
