### ISSUE TITLE
Export diagram as PNG file

### ISSUE THREAD

**Issue by BurningDev** [ModelioOpenSource/Modelio#82]
It would be very nice to be able to export diagrams directly as an image (preferably PNG file).

**Comment by IrinaNeculita** [comment]
Hello,
We have the option "Save diagram in a file", the extension is PNG.

![modelio_wplPjVP99s](https://github.com/ModelioOpenSource/Modelio/assets/130666068/e77f49fd-25c9-4878-ab9a-2d7baf4f5a2f)

Regards, 
Irina
