### ISSUE TITLE
The xmi output problem with boundary in use case diagram

### ISSUE THREAD

**Issue by acb18hl** [ModelioOpenSource/Modelio#9]
Hi, I have found that Modelio is really good approach to create UML diagram and it is really helpful to me. However, I have some problem with the xmi output file. Do you mind spending some time to give me some suggestions?
I have checked some Modelio tutorial video and official website. Then I have used rectangle to represent the system boundary for use case diagram. 
Therefore, I have created two use case in boundary and two actors in the outside of the boundary.

I have also export it to xmi file and check it. It only include 7 packed element which are 3 association, 2 actors and 2 usecase nodes. The boundary element could not showed in the Modelio xmi output.

**Comment by modelio-cde** [comment]
Hi,

To represent the system boundary (i.e. the element to which the UseCases belong) in a Use Case diagram, you just need to check the "Show System Boundary" tick-box in the diagram's symbol tab :

![SystemBoundary](https://user-images.githubusercontent.com/70592819/104921470-a5b67a80-5999-11eb-9b11-e4faa355e84d.png)

The "rectangle" you used is not a model element, just a drawing in the diagram, therefore it is not managed by XMI.

In the example shown above, the system boundary beeing the parent package of the UseCase it will be exported in the XMI file.
Diagrams however are not exported by XMI.

Hope this help,
cde.
