### ISSUE TITLE
Java Designer : update model from sources fails

### ISSUE THREAD

**Issue by marcadetd** [ModelioOpenSource/Modelio#91]
Hi,
With the latest version of Modelio (5.4.1), when trying to update model from Java source code, the following error is displayed:
![JavaReverse](https://github.com/ModelioOpenSource/Modelio/assets/20811322/f7107375-9159-47af-b600-4ea020324757)
It was OK with Modelio 5.3.
It may be related to #88?

**Comment by modelio-cde** [comment]
Hi, 

A fix has been done in the JavaDesigner 5.4.02 version of the module, the reverse and update are now working fine.
You can download it here : 
https://github.com/ModelioOpenSource/ExtensionsForModelio/releases/download/v5.4.1/JavaDesigner_5.4.02.jmdac

Best regards,
cde.
