### ISSUE TITLE
Cannot hide/mask name of extension point on <<Extends>> relationship line

### ISSUE THREAD

**Issue by bobhairgrove** [ModelioOpenSource/Modelio#93]
I have use cases with extension points and other use cases which are in a _«Extend»_ relation to the main use case as in the following diagram. This is to express as UML the main menu and its submenus which are to appear in the GUI of my application.

The extension points are already defined in the main (target) use case, but I cannot mask the duplicate name which appears on the line. When I select just the label, and select "Mask Selection" from the context menu, it hides the entire line, which I do not want. However, I also do not want to clutter up the diagram by duplicating the names of the extension points.

Here is a sample part of the diagram:
![Use_Cases_cropped](https://github.com/ModelioOpenSource/Modelio/assets/10685967/6f8f713e-fe70-4aea-b152-18acaad9f69f)

My Modelio version is here:
![about_Modelio](https://github.com/ModelioOpenSource/Modelio/assets/10685967/b7021bca-ac01-4d49-bb11-e6aac5596bab)

Is there some way to accomplish this?

Also, is there a way to increase the margin of whitespace around the diagram (without resorting to tricks such as creating text labels with invisible characters such as non-breaking spaces)?

**Comment by bobhairgrove** [comment]
I just installed the newest Modelio (5.4), and the issue still exists.

If I do not reference an extension point in the target use case, Audit reports this as an error. If I select the extension point, it shows it on the diagram, and I cannot hide it.

**Comment by IrinaNeculita** [comment]
Hi,
No, the label for "extension relationship" cannot be hide.  
Audit displays an "advice", R2900.

**Comment by bobhairgrove** [comment]
Perhaps it is not a good idea to express menus and submenus like this in UML?

I think I will use packages with use cases instead of extension points. The menus which contain submenus or menu items have no functionality independent of the menu items, so maybe these higher-up menus would be best modelled as packages?
