### ISSUE TITLE
Export diagrams as SVG images

### ISSUE THREAD

**Issue by yaasiin-ayeva** [ModelioOpenSource/Modelio#94]
Hello everyone. 

I was wondering if there's a way for exporting diagrams as svg images ? 

I tried but the only formats i'm getting are PNG, BMP, JPEG, GIF. 

I am actually using Modelio 4.1.00 on Linux.

Thanks

**Comment by IrinaNeculita** [comment]
Hello,
No, it is not possible to save as svg. Only the  PNG, BMP, JPEG, GIF are available.

Regards,
Irina.
