### ISSUE TITLE
Delete Element From Diagram Also Delete From Model

### ISSUE THREAD

**Issue by robertbui** [ModelioOpenSource/Modelio#95]
When I want to delete an element from a diagram e.g. class diagram, Modelio 5.4. The element is deleted from diagram. This is good.
However, the element also deleted from the model structure. This is not the most desirable effect.
For example, I create an element for in a class diagram but I want to remove it but I still want to keep the element for later use. If that get deleted from the model, I can not use it any longer. It is annoying when I have large structure that I want to refactor.
The desirable solution should be to have two deletion actions: 
1. Delete from diagram
2. Delete from model (and also delete from diagram).

**Comment by BigSchtroumpf** [comment]
Modelio already supports two distinctive "delete" commands.
Deleting from diagram only (ie the deleted model element remains present in the model and only its representation in the diagram is removed) is called "unmask" (CTRL-M if I remember well). 
To summarize:
- unmask (CTRL_M) delete from diagram only
- delete (DEL) delete from both diagram and model)

Additionally there is an option in the Modelio preferences to change the "DEL" shortcut behavior to an equivalent of the 
"unmask" command I described above. Using this options you get:
- DEL => delete from diagram only
- CTRL-M => unmask ie delete from diagram only
- SHIFT-DEL => delete from both diagram and model.



Hope that helps.

**Comment by robertbui** [comment]
Glad to know and thanks for the reply.
I did not immediately associate "masking" with delete from diagram only. Maybe, I have a simple mind and got used to other tools the specifically say "Delete from diagram" & "Delete from model" in the context menu.

But it's all good. Each tool have their own terminologies that I have to get used to.

Thanks again.
