### ISSUE TITLE
Cannot reorder attributes within a class

### ISSUE THREAD

**Issue by JAngstadt** [ModelioOpenSource/Modelio#98]
My apologies if I'm missing something super obvious, but I'm completely stumped on how to do this. I simply want to reorder the attributes in a class on my Class Diagram. I've looked through the documentation, online forums, StackOverflow, even tried ChatGPT, and no where seems to have any notes on how to do this. If anyone has any tips it would be greatly appreciated. Thanks!

ETA: I'm running Modelio 5.4

**Comment by IrinaNeculita** [comment]
Hello,
You can change the order of operations and attributes.
Select the class: go to symbol view: set the automatic content on manual
In explorer move the operation/attributes as you wish using the move up/down arrows.
See the attached gif.

![order attributes](https://github.com/ModelioOpenSource/Modelio/assets/130666068/3d3aac44-431e-4a70-a881-2c18d81bf50e)

Hope the information it is solving your problem.

Regards,
Irina.
