### ISSUE TITLE
State Machine Transition Actions do not appear on diagram

### ISSUE THREAD

**Issue by bdebruyn** [ModelioOpenSource/Modelio#99]
State Machine diagrams do not show the action part of a transition. For example, {state} -> evEvent[condition]/action()->{state1}.

Added State Machine to Class
Added "Operation" as an operation to Class
In the diagram I connected to state with a transition
Opened the dialog box to edit transition
Added "Operator()" to Expression of action, which appears as "O() +Operation()" 

![Screenshot from 2024-05-17 12-04-52](https://github.com/ModelioOpenSource/Modelio/assets/50416365/1896ae35-424a-417d-8892-9b69accc0324)

**Comment by IrinaNeculita** [comment]
Hello, 
From Symbol view should check show label for transition 


![modelio_sH5U6Ved8u](https://github.com/ModelioOpenSource/Modelio/assets/130666068/1dfd0d46-cd6d-4e5e-9f26-c847534e1aa7)
